Fix DNS capture issue on systemd based OS
sshuttle/sshuttle pull request #726
Opened 2022-02-02 01:15 UTC by william-frank

On systemd based systems /etc/resolve.conf contains only the link to localhost.
This forces all dns requests to be sent to the systemd DNS subsystem on 12.0.0.1.
Capturing DNS requests to 127.0.0.1 will result in an endless loop and will prevent any DNS names from being resolved.

This fix ensures that we only capture remote DNS requests, preserving the systemd dns proxy.

2022-02-02 16:32 UTC, skuhl commented
I don't think I understand the endless loop problem and can't reproduce it. On my machine /etc/resolv.conf points to 127.0.0.53 (i.e., localhost). If I run sshuttle with --dns and then run "dig @127.0.0.53 example.com", the request is intercepted by shuttle, resolved remotely and the response is sent back correctly.

That said, I agree that it is unclear if we should be capturing DNS requests sent to localhost or if we should just capture DNS requests that leave the machine. One argument for including it (assuming it doesn't cause trouble), is that systemd's resolver could start using methods that we might not be able to intercept in the future (DNS over HTTPS or similar). In that case, we can intercept the plain DNS request going to localhost, but wouldn't be able to intercept the outgoing DNS over HTTPS request that it might create. However, as far as I know, systemd's resolver doesn't support that yet.

2022-02-02 17:45 UTC, william-frank commented
Hi Scott,
Appreciate you coming back to me on this.
I'm really surprised that it works for you without this fix. I've tested on
Ubuntu 20.04+ as well as on a Raspbian 11 and without this fix the system
can't resolve any names at all.
One additional setting that I do have however is --listen 0.0.0.0 as I'm
using sshuttle as a poor mens VPN.

>>systemd's resolver could start using methods that we might not be able to
intercept in the future
That does makes sense. The only reason I had to dig into and come up with
this fix was because my system would not be able to resolve any names what
so ever.

Best Regards,
William



On Wed, Feb 2, 2022 at 11:32 AM Scott Kuhl ***@***.***> wrote:

> I don't think I understand the endless loop problem and can't reproduce
> it. On my machine /etc/resolv.conf points to 127.0.0.53 (i.e., localhost).
> If I run sshuttle with --dns and then run "dig @127.0.0.53 example.com",
> the request is intercepted by shuttle, resolved remotely and the response
> is sent back correctly.
>
> That said, I agree that it is unclear if we should be capturing DNS
> requests sent to localhost or if we should just capture DNS requests that
> leave the machine. One argument for including it (assuming it doesn't cause
> trouble), is that systemd's resolver could start using methods that we
> might not be able to intercept in the future (DNS over HTTPS or similar).
> In that case, we can intercept the plain DNS request going to localhost,
> but wouldn't be able to intercept the outgoing DNS over HTTPS request that
> it might create. However, as far as I know, systemd's resolver doesn't
> support that yet.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sshuttle/sshuttle/pull/726#issuecomment-1028123935>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJX7H5HB3HLQSIC7EMES2YTUZFMDNANCNFSM5NKXXNJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-03 22:35 UTC, brianmay commented
I think a problem with this change is that `systemd_resolved` is set to True on non-systemd systems, on the client.

https://github.com/william-frank/sshuttle/blob/16b1401194783a049009ddf58fc230849ea18cb3/sshuttle/client.py#L733

So this change will break non-systemd client systems, which don't have the systemd resolv.conf file.

Curiously, on the server it is always set to False (via another function):

https://github.com/william-frank/sshuttle/blob/16b1401194783a049009ddf58fc230849ea18cb3/sshuttle/server.py#L185

Maybe the name of the parameter `systemd_resolved` is confusing, and it should be changed.

2022-02-03 22:41 UTC, william-frank commented
Maybe it makes sense to implement a check instead - if there is systemd resolv.conf - then use that, otherwise /etc/resolv.conf ?
The issue is that for me the package doesn't work at all when including 127.0.0.53 (Ubuntu 21.10) which is specified in /etc/resolve.conf

2022-02-04 02:36 UTC, skuhl commented
I'm also using Ubuntu 21.10 and can't reproduce it. Which sshuttle method are you using? The default nat method? I wish I could reproduce it so I could understand the issue better. I would have expected we'd see more reports of issues about this if the problem were common.

2022-02-04 02:56 UTC, skuhl commented
> So this change will break non-systemd client systems, which don't have the systemd resolv.conf file.

Right, I believe that is correct.

> Curiously, on the server it is always set to False (via another function):

This is as intended. The logic is that we should use the DNS server that everything else on the remote host is using: The one specified in /etc/resolv.conf (which happens to be the systemd stub resolver). By setting this flag to false and only using /etc/resolv.conf, it means that sshuttle will act similarly to all of the other programs doing DNS resolution on the remote host. If there is a good reason to do this differently, I'm open to hearing about it.

> Maybe the name of the parameter `systemd_resolved` is confusing, and it should be changed.

It currently means "use /etc/resolv.conf and sytemd's resolv.conf" and setting it to false just uses /etc/resolv.conf. I'd be supportive of a clearer name.

2022-02-04 22:00 UTC, brianmay requested changes
As discussed the logic as written will break systems that are not using systemd-resolv.

Not sure what the solution is. We could check for the existence of that file I guess. But does the existence of the file really mean we are actively using systemd-resolv? e.g. it may have been disabled.

2025-02-08 22:40 UTC, brianmay commented
No updates in last 3 years. Closing.

Can be reopened if anybody wants to take over.

2025-02-08 22:40 UTC, closed without merging